### SPRING ###
spring:
  application:
    name: "@project.name@"
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:alten
    username: alten
    password:

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bdd_alten_ce
#    username: root

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
